// <auto-generated />
using System;
using Hub.MoneTrik.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hub.MoneTrik.Infrastructure.Migrations
{
    [DbContext(typeof(HubMonetrikContext))]
    [Migration("20250715164255_CriandoTabelaDespesas")]
    partial class CriandoTabelaDespesas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Hub.Monetrik.Domain.Models.Entities.Despesa.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria")
                        .HasColumnType("int")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("DataInicioPagamento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_vencimento");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_registro");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("int")
                        .HasColumnName("numero_parcela");

                    b.Property<int>("Situacao")
                        .HasColumnType("int")
                        .HasColumnName("situacao");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext")
                        .HasColumnName("titulo");

                    b.Property<decimal>("TotalParcelas")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_parcelas");

                    b.Property<decimal>("ValorParcela")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_parcela");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.ToTable("despesas");
                });
#pragma warning restore 612, 618
        }
    }
}
